// CONSTANTS.H


#define SCALE_FACTOR 9
#define EVEN_HEIGHT_OFFSET 4
#define ODD_HEIGHT_OFFSET 4

#define START_VIEW_RADIUS 4.5
#define BASE_CACHE_SIZE 400
#define MIN_CITY_SPACE 3
#define CITY_COUNT_PER_CELL 5
